Repository rsksmart/rif-identity-manager, pull requests merged in 2020-12, with the labels that each got.

#14 Data vault view insert
  package.json
  src/app/App.tsx
  src/app/Authenticated/AuthenticatedComponent.tsx
  src/app/Authenticated/AuthenticatedContainer.ts
  src/app/Authenticated/components/Header.test.tsx
  src/app/Authenticated/components/HeaderComponent.tsx
  src/app/Authenticated/components/Navigation.test.tsx
  src/app/Authenticated/components/Navigation.tsx
  src/app/Dashboard/DashboardScreen.tsx
  src/app/DataVault/DataVaultComponent.tsx
  src/app/DataVault/DataVaultContainer.ts
  src/app/DataVault/panels/AddDeclarativeDetails.test.tsx
  src/app/DataVault/panels/AddDeclarativeDetails.tsx
  src/app/DataVault/panels/DeclarativeDetailsDisplay.test.tsx
  src/app/DataVault/panels/DeclarativeDetailsDisplay.tsx
  src/app/state/configureStore.ts
  src/app/state/operations/datavault.ts
  src/app/state/operations/identity.ts
  src/app/state/operations/tokens.ts
  src/app/state/reducers/datavault.test.ts
  src/app/state/reducers/datavault.ts
  src/assets/images/icons/declarative-details.svg
  src/assets/images/icons/upload.svg
  src/assets/scss/_forms.scss
  src/assets/scss/_grid.scss
  src/assets/scss/_index.scss
  src/assets/scss/_table.scss
  src/assets/scss/components/_alert.scss
  src/assets/scss/components/_button.scss
  src/assets/scss/components/_navigation.scss
  src/assets/scss/screens/_data-vault.scss
  src/components/Loading/LoadingComponent.tsx
  src/components/Navigation/Navigation.tsx
  src/config/config.ethereum.json
  src/config/config.local.json
  src/config/config.mainnet.json
  src/config/config.testnet.json
  src/config/getConfig.ts
  src/providerContext.tsx
  yarn.lock
Labels: enhancement

#15 Create pr.yml
  .github/workflows/pr.yml
Labels: dev

#16 Fix pr.yml
  .github/workflows/pr.yml
  package.json
Labels: bug, dev
